# 🏆 Curso de Python para Análise de Futebol
**Nível:** Básico ao Intermediário
**Duração Estimada:** 3 horas

Bem-vindo! Este material foi feito sob medida para cientistas de dados do futebol. Aqui, você não vai calcular "a média de notas de alunos fictícios", você vai calcular a **taxa de conversão de chutes do Bruno Guimarães** e agrupar times por **saldo de gols**!\n

## ⚽ Módulo 1: O Absoluto Básico (Variáveis e Tipos)

No Python, armazenamos dados em **variáveis**. Pense numa variável como uma gaveta com um rótulo.
Em estatísticas de jogo, lidamos com diferentes tipos de dados:
- **Inteiros (`int`)**: Gols, assistências, cartões.
- **Ponto Flutuante (`float`)**: Distância percorrida (km), Nota Sofascore.
- **Strings (`str`)**: Texto (Nome do jogador, time).
- **Booleanos (`bool`)**: Verdadeiro/Falso (`True` / `False`).\n

In [2]:
# Variáveis Básicas de Futebol
nome_jogador = "Vini Jr"        # String
gols_marcados = 2               # Int
distancia_km = 10.5             # Float
foi_eleito_craque = True        # Bool

print(f"O jogador {nome_jogador} correu {distancia_km}km e marcou {gols_marcados} gols.")

O jogador Vini Jr correu 10.5km e marcou 2 gols.

### Operadores Matemáticos
Como calculamos métricas simples? Usamos `+`, `-`, `*`, `/`.
Se quisermos calcular o saldo de gols de um time em uma partida:\n

In [3]:
gols_pro = 3
gols_contra = 1
saldo_gols = gols_pro - gols_contra

jogos_disputados = 5
media_gols_por_jogo = gols_pro / jogos_disputados

print(f"Saldo: {saldo_gols}")
print(f"Média de Gols: {media_gols_por_jogo}")

Saldo: 2
Média de Gols: 0.6

### Exercício Prático 1
> **Desafio:** Crie variáveis para `passes_certos` (ex: 45) e `passes_totais` (ex: 50).
> Calcule a porcentagem de `precisao_passe` e imprima na tela.\n

In [4]:
# Seu código aqui:
passes_certos = 45
passes_totais = 50

# precisao_passe = (passes_certos / passes_totais) * 100
# print(...)

## 📊 Módulo 2: Estruturas de Dados e Fluxo

No mundo real, não temos apenas "1 jogador". Temos escalações inteiras!
Para lidar com vários dados, usamos **Listas** e **Dicionários**.

### Listas (`list`)
Uma lista armazena múltiplos valores na mesma "gaveta".\n

In [5]:
escalacao = ["Alisson", "Danilo", "Marquinhos", "Militão", "Wendell", "Casemiro", "Bruno Guimarães", "Paquetá", "Raphinha", "Vini Jr", "Rodrygo"]

print(f"Goleiro: {escalacao[0]}") # Em Python, contamos a partir do ZERO!
print(f"Ataque: {escalacao[8:]}") # Pegando do 8º jogador em diante

Goleiro: Alisson
Ataque: ['Raphinha', 'Vini Jr', 'Rodrygo']

### Dicionários (`dict`)
Extremamente importantes para APIs esportivas (como Sofascore, Wyscout). Um dicionário mapeia uma "Chave" para um "Valor" (Key -> Value).\n

In [6]:
# Perfil de um Jogador
scouts = {
    "nome": "Richarlison",
    "camisa": 9,
    "gols": 1,
    "assistencias": 0,
    "minutos_jogados": 75,
    "finalizacoes_no_alvo": 3
}

print(f"Jogador: {scouts['nome']}")
print(f"Gols: {scouts['gols']}")

Jogador: Richarlison
Gols: 1

### Fluxo Condicional (If / Elif / Else)
Como programamos o computador para tomar decisões analíticas?
Exemplo: Um scout precisa avaliar se um jogador deve ser contratado baseado na sua nota (Rating).\n

In [7]:
nota_sofascore = 7.8

if nota_sofascore >= 8.0:
    print("Contratar imediatamente! (Classe A)")
elif nota_sofascore >= 7.0:
    print("Monitorar desempenho. (Classe B)")
else:
    print("Abaixo da média da liga. (Classe C)")

Monitorar desempenho. (Classe B)

### Laços de Repetição (`for`)
Analisar dados muitas vezes significa olhar para muitos dados. O `for` repete uma ação para cada item em uma lista.\n

In [8]:
# Analisando a quantidade de passes de vários meio-campistas
passes_por_jogador = [45, 60, 32, 88, 12]

total_passes_time = 0
for passes in passes_por_jogador:
    total_passes_time += passes
    if passes > 50:
        print(f"Motorzinho do time! Fez {passes} passes.")
        
print(f"Total de passes da equipe: {total_passes_time}")

Motorzinho do time! Fez 60 passes.
Motorzinho do time! Fez 88 passes.
Total de passes da equipe: 237

### Exercício Prático 2
> **Desafio:** Você recebeu uma lista com as idades dos zagueiros: `idades = [22, 34, 28, 19, 31]`.
> Crie um laço `for` que imprima "Veterano" se a idade for >= 30 e "Jovem" se for < 30.\n

In [9]:
idades = [22, 34, 28, 19, 31]

# Seu código aqui:
# for idade in idades:
#    if ...

## ⚙️ Módulo 3: Funções (Modularização)

Se você repete o mesmo cálculo de performance o tempo todo, crie uma **Função**.
Uma função é uma fábrica: você entra com matéria-prima (Parâmetros) e sai com um produto final (Retorno).\n

In [10]:
def calcular_minutos_por_gol(minutos_jogados, gols):
    # Tratamento de erro básico (Não dividir por zero)
    if gols == 0:
        return "Não marcou"
    
    return round(minutos_jogados / gols, 1)

# Testando a função com dois atacantes
minutos_a1 = calcular_minutos_por_gol(450, 5) # 5 gols em 450 min
minutos_a2 = calcular_minutos_por_gol(600, 0) # 0 gols em 600 min

print(f"Atacante 1 precisa de {minutos_a1} mins para fazer um gol.")
print(f"Atacante 2: {minutos_a2}")

Atacante 1 precisa de 90.0 mins para fazer um gol.
Atacante 2: Não marcou

### Tratamento de Erros Moderno (`try / except`)
Às vezes recebemos dados sujos da API e o Python quebra (Erro). O `try / except` nos protege.\n

In [11]:
api_data = {"passes": 50, "certos": "Quarenta"} # O dado veio como texto!

try:
    precisao = api_data['certos'] / api_data['passes']
    print(precisao)
except TypeError:
    print("ERRO DE DADOS: O número de passes certos veio como texto (string). Precisamos higienizar a base!")
except KeyError:
    print("ERRO DE DADOS: A chave 'certos' não existe no JSON.")

ERRO DE DADOS: O número de passes certos veio como texto (string). Precisamos higienizar a base!

## 🐼 Módulo 4: Ponte para Ciência de Dados (Introdução ao Pandas)

Você chegou no nível intermediário! Na vida real da análise de dados de futebol, não iteramos listas com o comando `for` toda hora. Nós usamos a biblioteca **Pandas**. Ela é como um Excel com "esteróides".

O formato tabular principal do Pandas se chama **DataFrame**.\n

In [12]:
# O Pandas não vem nativo, precisamos importá-lo!
import pandas as pd
from IPython.display import display

# Simulando um extrato tático extraído do Sofascore
dados = {
    "Jogador": ["Ederson", "Casemiro", "Paquetá", "Vini Jr", "Endrick"],
    "Posicao": ["GK", "VOL", "MEI", "ATA", "ATA"],
    "Nota": [7.1, 8.2, 7.5, 9.0, 8.0],
    "Gols": [0, 0, 1, 2, 1],
    "Passes_Tentados": [25, 80, 60, 20, 10]
}

# Transformando o Dicionário em um DataFrame do Pandas
df = pd.DataFrame(dados)

# .head() exibe as 5 primeiras linhas da "planilha"
display(df.head())

    Jogador Posicao  Nota  Gols  Passes_Tentados
0   Ederson      GK   7.1     0               25
1  Casemiro     VOL   8.2     0               80
2   Paquetá     MEI   7.5     1               60
3   Vini Jr     ATA   9.0     2               20
4   Endrick     ATA   8.0     1               10

### Filtros Mágicos do Pandas
Filtramos dezenas de milhares de linhas instantaneamente.\n

In [13]:
# Filtrar apenas os Atacantes
atacantes = df[df['Posicao'] == 'ATA']
display(atacantes)

   Jogador Posicao  Nota  Gols  Passes_Tentados
3  Vini Jr     ATA   9.0     2               20
4  Endrick     ATA   8.0     1               10

In [14]:
# Filtrar jogadores com Nota maior ou igual a 8.0
craques = df[df['Nota'] >= 8.0]
display(craques)

    Jogador Posicao  Nota  Gols  Passes_Tentados
1  Casemiro     VOL   8.2     0               80
3   Vini Jr     ATA   9.0     2               20
4   Endrick     ATA   8.0     1               10

In [15]:
# Criando uma coluna nova calculada! (Ex: Participações Diretas = Gols + 0 Assistencias pro exemplo)
df['Participacoes'] = df['Gols'] * 1 
display(df)

    Jogador Posicao  Nota  Gols  Passes_Tentados  Participacoes
0   Ederson      GK   7.1     0               25              0
1  Casemiro     VOL   8.2     0               80              0
2   Paquetá     MEI   7.5     1               60              1
3   Vini Jr     ATA   9.0     2               20              2
4   Endrick     ATA   8.0     1               10              1

### Agrupamentos Simples
Quem é a média de notas por Posição? (Groupby)\n

In [16]:
media_por_posicao = df.groupby('Posicao')['Nota'].mean()
display(media_por_posicao)

Posicao
ATA    8.5
GK     7.1
MEI    7.5
VOL    8.2
Name: Nota, dtype: float64

### Desafio Final 🏆
> Use o DataFrame `df` que criamos acima.
> 1. Filtre apenas jogadores que deram mais de 40 `Passes_Tentados`.
> 2. Guarde na variável `jogadores_passadores` e exiba o resultado.
\n

In [17]:
# Seu código aqui:

# jogadores_passadores = df[ ... ]
# display(jogadores_passadores)

---
## Fim do Curso Básico/Intermediário!
Se você compreendeu a lógica deste Notebook, você está pronto para importar os JSONs do **Sofascore** e criar Mapas de Calor, Mapas de Passes e os Dashboards robustos nas próximas sessões do nosso curso na CBF Academy!\n